<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildThisFileDirectory)/../../TugDSC.common.props" Condition="'$(TugDSC_common_props)' == ''" />
  <Import Project="$(MSBuildThisFileDirectory)/../../TugDSC.sharedasm.props" Condition="'$(TugDSC_sharedasm_props)' == ''" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NoWarn>$(NoWarn);$(CommonNoWarn)</NoWarn>
    <RootNamespace>TugDSC</RootNamespace>
    <AssemblyTitle>TugDSC Abstractions</AssemblyTitle>
    <AssemblyDescription>Common Abstractions &amp; Components</AssemblyDescription>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="System.Composition" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="8.0.2" />
  </ItemGroup>
</Project>
